 baseURL = 'https://ekaterina-blog.pages.dev/'
 languageCode = 'ja'
 languageName = 'Japanese'
 defaultContentLanguage = 'ja'
 hasCJKLanguage = true
 title = 'えかてりーなのゆるブログ'
 theme = 'ananke'
 
 [params]
   text_color = 'dark-gray'
   background_color_class = 'bg-navy'
   author = 'えかてりーな'
   favicon = '/images/profile.png'
   site_logo = '/images/profile.png'
 
 [[params.ananke_socials]]
   name = 'twitter'
   url  = 'https://twitter.com/Ekaterinajp_se'
